---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  tasks:
    - name: Register windows with surveys
      ansible.builtin.find:
        paths: ./windows/with_survey
        file_type: directory
      register: windows_with_survey

    # - name: Create Windows patching
    #  ansible.controller.job_template:
    #    name: 'Windows // Windows Update'
    #    job_type: "run"
    #    organization: "Default"
    #    inventory: "Lab Inventory"
    #    project: "playbook"
    #    playbook: "Windows/windows_updates.yml"
    #    state: "present"
    #    survey_enabled: true
    #    survey_spec: "{{ lookup('file', 'my_survey.json') }}"
