---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Register windows with surveys
      ansible.builtin.find:
        paths: ./windows/with_survey
        file_type: directory
      register: windows_with_survey

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "{{ (item.path | split('/'))[2] }}"
      with_items: "{{ windows_with_survey.files }}"

    - name: Create Windows templates with surveys
      ansible.controller.job_template:
        name: "Windows // {{ (item.path | split('/'))[2] }}"
        job_type: "run"
        organization: "Default"
        inventory: "Lab Inventory"
        project: "playbook"
        playbook: "{{ item.path }}/{{ (item.path | split('/'))[2] }}.yml"
        state: "present"
        survey_enabled: true
        #survey_spec: "{{ lookup('file', 'my_survey.json') }}"
      with_items: "{{ windows_with_survey.files }}"
