---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create labels
      ansible.controller.label:
        name: "{{ item }}"
        organization: "Default"
      loop:
        - "RHEL"
        - "Windows"
        - "AAP"

    - name: Register windows with surveys
      ansible.builtin.find:
        paths: ./windows/with_survey
        file_type: directory
      register: windows_with_survey

    - name: Create Windows templates with surveys
      ansible.controller.job_template:
        name: "Windows // {{ (item.path | split('/'))[2] }}"
        labels:
          - "Windows"
        job_type: "run"
        organization: "Default"
        inventory: "Lab Inventory"
        project: "playbooks"
        playbook: "{{ item.path }}/{{ (item.path | split('/'))[2] }}.yml"
        state: "present"
        credential: "Windows AD Admin"
        survey_enabled: true
        survey_spec: "{{ lookup('file', (item.path + '/' + (item.path | split('/'))[2] + '.json')) }}"
      with_items: "{{ windows_with_survey.files }}"

    - name: Register windows without surveys
      ansible.builtin.find:
        paths: ./windows/without_survey
        file_type: directory
      register: windows_without_survey

    - name: Create Windows templates without surveys
      ansible.controller.job_template:
        name: "Windows // {{ (item.path | split('/'))[2] }}"
        labels:
          - "Windows"
        job_type: "run"
        organization: "Default"
        inventory: "Lab Inventory"
        project: "playbooks"
        playbook: "{{ item.path }}/{{ (item.path | split('/'))[2] }}.yml"
        state: "present"
        credential: "Windows AD Admin"
      with_items: "{{ windows_without_survey.files }}"

    - name: Register RHEL with surveys
      ansible.builtin.find:
        paths: ./rhel/with_survey
        file_type: directory
      register: rhel_with_survey

    - name: Create RHEL templates with surveys
      ansible.controller.job_template:
        name: "RHEL // {{ (item.path | split('/'))[2] }}"
        labels:
          - "RHEL"
        job_type: "run"
        organization: "Default"
        inventory: "Lab Inventory"
        project: "playbooks"
        playbook: "{{ item.path }}/{{ (item.path | split('/'))[2] }}.yml"
        state: "present"
        credential: "RHEL Admin"
        survey_enabled: true
        survey_spec: "{{ lookup('file', (item.path + '/' + (item.path | split('/'))[2] + '.json')) }}"
      with_items: "{{ rhel_with_survey.files }}"

    - name: Register RHEL without surveys
      ansible.builtin.find:
        paths: ./rhel/without_survey
        file_type: directory
      register: rhel_without_survey

    - name: Create RHEL templates without surveys
      ansible.controller.job_template:
        name: "RHEL // {{ (item.path | split('/'))[2] }}"
        labels:
          - "RHEL"
        job_type: "run"
        organization: "Default"
        inventory: "Lab Inventory"
        project: "playbooks"
        playbook: "{{ item.path }}/{{ (item.path | split('/'))[2] }}.yml"
        state: "present"
        credential: "RHEL Admin"
      with_items: "{{ rhel_without_survey.files }}"

# Special boys
    - name: Create Refresh RHAH token template
      ansible.controller.job_template:
        name: 'AAP // Refresh RHAH token'
        job_type: "run"
        organization: "Default"
        inventory: "Lab Inventory"
        project: "aap-config"
        playbook: "aap/refresh-rhah-token.yml"
        state: "present"
        labels:
          - "AAP"
        extra_vars:
          user_token: "in keeper, change me"

    - name: Schedule token refresh template
      ansible.controller.schedule:
        name: "Sunday weekly"
        state: present
        unified_job_template: 'AAP // Refresh RHAH token'
        rrule: "DTSTART:20250119T040000Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"
