- name: Metrics test
  hosts: localhost
  tasks:
    - name: Metrics test
      ansible.builtin.uri:
        url: 'https://aap-aap.apps.mitchell-labs.mikemitchell.info/api/controller/v2/host_metrics/'
        method: GET
        url_username: admin
        url_password: zYmihXnoShuRa1KOBCjelQCXFubzGIjC
        validate_certs: false
        follow_redirects: safe
      register: result
