- name: RHEL install zabbix agent
  become: true
  become_user: root
  hosts: "{{ rhel_hosts | default('rhel') }}"
  vars:
    zabbix_server: "zabbix.mikemitchell.info"
    rpm_url: "https://repo.zabbix.com/zabbix/7.2/release/rhel/9/noarch/zabbix-release-latest-7.2.el9.noarch.rpm"
  tasks:
    - name: Add Zabbix repos
      ansible.builtin.dnf:
        name: "{{ rpm_url }}"
        state: present
        disable_gpg_check: true

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - "zabbix-agent2"
          - "firewalld"
          - python3-firewall
        state: present
        disable_gpg_check: true

    - name: Stop agent service, if started
      ansible.builtin.service:
        name: zabbix-agent2
        state: stopped

    - name: Copy config file template
      ansible.builtin.template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        mode: '0644'

    - name: Start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Enable firewall for zabbix-agent2
      ansible.posix.firewalld:
        service: '{{ item }}'
        state: enabled
        immediate: true
        permanent: true
      loop:
        - 'zabbix-agent'
        - 'Zabbix Trapper'

    - name: Start and enable agent service
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
        enabled: true
