- name: RHEL install zabbix agent
  become: true
  become_user: root
  hosts: "{{ rhel_hosts | default('rhel') }}"
  vars:
    zabbix_server: "zabbix.mikemitchell.info"
    rpm_url: "https://repo.zabbix.com/zabbix/7.2/release/rhel/9/noarch/zabbix-release-latest-7.2.el9.noarch.rpm"
  tasks:
    - name: Install the nginx rpm from a remote repo
      ansible.builtin.dnf:
        name: "{{ rpm_url }}"
        state: present
        disable_gpg_check: true
