- name: RHEL install zabbix agent
  become: true
  become_user: root
  hosts: "{{ rhel_hosts | default('rhel') }}"
  vars:
    zabbix_server: "zabbix.mikemitchell.info"
  roles:
    - role: zabbix.zabbix.agent
      agent_variant: 2
      agent_major_version: 7.2
      agent_param_server: "{{ zabbix_server }}"
      agent_param_serveractive: "{{ zabbix_server }}"
      agent_param_hostmetadata: 'RHEL Servers'
