---
- hosts: "{{ windows_host }}"

  tasks:
    - name: Register partition number
      ansible.windows.win_powershell:
        script: |
          (Get-Partition -DriveLetter {{ drive_letter }}).PartitionNumber
      register: partition_number

    - name: Register disk number
      ansible.windows.win_powershell:
        script: | 
          (Get-Partition -DriveLetter {{ drive_letter }} | Get-Disk).Number
      register: disk_number

    - name: Resize partition
      community.windows.win_partition:
        drive_letter: "{{ drive_letter }}"
        partition_size: -1
        partition_number: "{{ partition_number.output[0] }}"
        disk_number: "{{ disk_number.output[0] }}"
