---
- hosts: "{{ windows_host }}"

  tasks:
    - name: Register partition number
      ansible.windows.win_powershell:
        script: |
          (Get-Partition -DriveLetter {{ drive_letter }}).PartitionNumber
      register: partition_number

    - name: Register disk number
      ansible.windows.win_powershell:
        script: | 
          (Get-Partition -DriveLetter {{ drive_letter }} | Get-Disk).Number
      register: disk_number
