---
- name: Configure RHEL 9 as a Reverse Proxy
  hosts: "{{ rhel_hosts }}"
  become: yes
  vars:
    ssl_cert_path: "/etc/nginx/ssl/mikemitchell.info.crt"
    ssl_key_path: "/etc/nginx/ssl/mikemitchell.info.key"
  tasks:
    - name: Install Nginx and OpenSSL
      ansible.builtin.dnf:
        name:
          - nginx
          - openssl
        state: present

    - name: Ensure SSL directory exists
      ansible.builtin.file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'

    - name: Generate self-signed SSL certificate
      ansible.builtin.command: >
        openssl req -new -x509 -nodes -days 365 -subj "/CN={{ server_name }}" 
        -out {{ ssl_cert_path }} -keyout {{ ssl_key_path }}
      args:
        creates: "{{ ssl_cert_path }}"

    - name: Ensure Nginx is enabled and started
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Configure Nginx reverse proxy
      ansible.builtin.template:
        src: nginx_reverse_proxy.conf.j2
        dest: /etc/nginx/conf.d/reverse_proxy.conf
      notify: Restart Nginx

    - name: Ensure firewall allows HTTPS traffic
      ansible.posix.firewalld:
        service: https
        permanent: yes
        state: enabled
      notify: Reload Firewalld

  handlers:
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - name: Reload Firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
