---
- name: Expand PVC
  hosts: localhost
  tasks:
    - name: Register all disks
      ansible.builtin.set_fact:
        vm_disks: "{{ hostvars[vm_name]['vmi_volume_status'] }}"
      when: vm_name is defined

    - name: Find the one we care about
      ansible.builtin.set_fact:
        disk_to_expand_index: "{{ lookup('ansible.utils.index_of', vm_disks, 'eq', vm_disk_name, 'name') }}"
      when: vm_name is defined

    - name: Register that one
      ansible.builtin.set_fact:
        pvc_name: "{{ vm_disks[disk_to_expand_index | int].persistentVolumeClaimInfo.claimName }}"
      when: vm_name is defined

    - name: Expand the PVC
      redhat.openshift.k8s:
        state: present
        definition:
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            name: "{{ pvc_name }}"
            namespace: "{{ project_name }}"
          spec:
            resources:
              requests:
                storage: "{{ expansion_size }}"

    - name: Wait for PVC to be bound
      kubernetes.core.k8s_info:
        namespace: "{{ project_name }}"
        kind: PersistentVolumeClaim
        name: "{{ pvc_name }}"
      register: pvc_status
      retries: 10
      delay: 5
      until: "'conditions' not in pvc_status.resources[0].status"
