---
- name: Expand PVC
  hosts: localhost
  tasks:
    - name: Get VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm_info:
        name: "{{ vm_name }}"
        namespace: "{{ project_name }}"
      register: vm_info
      when: vm_name is defined

    - name: Print var
      ansible.builtin.debug:
        var: vm_info
