---
- name: Expand PVC
  hosts: localhost
  tasks:
    - name: Register Disk Object
      ansible.builtin.set_fact:
        vm_disks: "{{ hostvars['windemo01.mikemitchell.info']['vmi_volume_status'] }}"

    - name: Register Disk Object
      ansible.builtin.set_fact:
        disk_to_expand_index: "{{ lookup('ansible.utils.index_of', vm_disks, 'eq', 'volume-d', 'name') }}"

    - name: Register Disk Object
      ansible.builtin.set_fact:
        disk_to_expand: "{{ vm_disks[disk_to_expand_index] }}"

    - name: Print
      ansible.builtin.debug:
        var: disk_to_expand
