- name: AD // User Lookup
  hosts: windc01.mikemitchell.info

  tasks:
    - name: Get AD user information
      ansible.windows.win_powershell:
        script: "Get-ADUser -Identity {{ ad_user }}"
      register: ad_info

    - name: Get cat fact
      ansible.builtin.uri:
        url: https://catfact.ninja/fact
        method: GET
      register: cat_fact
      delegate_to: localhost

    - name: Print user info
      ansible.builtin.debug:
        msg: 
          - "UPN: {{ ad_info.output[0].UserPrincipalName }}"
          - "SamAccountName: {{ ad_info.output[0].SamAccountName }}"
          - "Favorite cat fact: {{ cat_fact.json.fact }}"