- name: AD // User Lookup
  hosts: windc01.mikemitchell.info

  tasks:
    - name: Get AD user information
      ansible.windows.win_powershell:
        script: "Get-ADUser -Identity {{ ad_user }}"
      register: ad_info

    - name: Print user info
      debug:
        msg: 
          - "UPN: {{ ad_info.output[0].UserPrincipalName }}"
          - "SamAccountName: {{ ad_info.output[0].SamAccountName }}"