- name: RHEL updates
  become: true
  become_user: root
  hosts: "{{ rhel_hosts | default('rhel') }}"
  tasks:
    - name: print fact
      ansible.builtin.debug:
        print: "{{ ansible_facts[ansible_local][custom][owner] }}"
    
    - name: Update all installed packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
        update_only: true
      register: update_status

    - name: Remove packates not needed anymore
      ansible.builtin.dnf:
        autoremove: true
