- name: RHEL install zabbix agent
  become: false
  hosts: localhost
  vars:
    zabbix_server: "zabbix.mikemitchell.info"
  roles:
    - role: zabbix.zabbix.host
      host_zabbix_api_server: "{{ zabbix_server }}"
      host_zabbix_api_url: "zabbix"
      host_templates: ["Linux by Zabbix agent"]  # Assign list of templates to the host;
      host_hostgroups: ["Linux servers"]
      host_zabbix_api_token: "{{ api_token }}"
      host_interfaces:
        - type: agent
          dns: "{{ new_zabbix_host }}"
