---
- hosts: "{{ windows_host }}"
  vars:
    iis_root: "C:\\Inetpub\\wwwroot"
    site_dest: "{{ iis_root }}\\source.zip"

  tasks:
  - name: Install IIS
    ansible.windows.win_feature:
      name: Web-Server
      state: present

  - name: Start IIS service
    ansible.windows.win_service:
      name: W3Svc
      state: started
